name: Python workflow

on:
  push:
    branches: [main ]
  pull_request:
    branches: [ main ]

jobs:
  python_ci:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - name: Run Cimon
      uses: cycodelabs/cimon-action@v0
      with:
        client-id: ${{ secrets.CIMON_CLIENT_ID }}
        secret: ${{ secrets.CIMON_SECRET }}

    - name: Create Next Snapshot Pull Request
      uses: peter-evans/create-pull-request@v4
      if: env.RELEASE_OK == 'yes'
      with:
        token: ${{ steps.generate-token.outputs.token }}
        commit-message: bump snapshot ${{ env.SC_NEXT_VERSION }}-SNAPSHOT
        title: 'bump snapshot ${{ env.SC_NEXT_VERSION }}-SNAPSHOT'

    - uses: actions/checkout@v2



    - name: nodejsscan scan
      uses: ajinabraham/njsscan-action@master
      with:
        args: '.'
        

    # - name: Publish package
    #   uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
    #   with:
    #     user: __token__
    #     password: ${{ secrets.PYPI_API_TOKEN }}

    # - uses: act10ns/slack@v1
    #     with:
    #       status: ${{ job.status }}
    #       steps: ${{ toJson(steps) }}
    #       channel: '#workflows'
    #     env:
    # ##      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}


    #- name: Deploy documentation
    #  uses: peaceiris/actions-gh-pages@v3
    #  with:
    #    github_token: ${{ secrets.GITHUB_TOKEN }}
    #    publish_dir: ./docs/_build/html
